[lrt] fix tests
Without this small change, the tests fail with:

```
$ python3 test/test_download.py TestDownload.test_LRT

F
======================================================================
FAIL: test_LRT (__main__.TestDownload):
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_download.py", line 218, in test_template
    expect_info_dict(self, tc_res_dict, tc.get('info_dict', {}))
  File "/home/giedrius/dev/yt-dlp/test/helper.py", line 258, in expect_info_dict
    self.assertFalse(

AssertionError: {'tags', 'thumbnail'} is not false : Missing keys in test definition: tags, thumbnail
```

Plus, there is a md5 hash related error after this one.