Fix GoPro extractor.
The extractor fails even when used on the URLs recorded in the tests
with an error like:

[GoPro] Extracting URL: https://gopro.com/v/KRm6Vgp2peg4e
[GoPro] KRm6Vgp2peg4e: Downloading webpage
ERROR: [GoPro] KRm6Vgp2peg4e: KRm6Vgp2peg4e: Failed to parse JSON (caused by JSONDecodeError('Expecting \',\' delimiter in \'"shop_url"=>"https:/\': line 1 column 5120 (char 5119)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/storage/avn/git/yt-dlp/yt_dlp/extractor/common.py", line 718, in extract
...

- The JSON in the webpage now contains colons as part of HTML entities
  such as &quot;. This makes the regexp used for matching truncate the
  JSON prematurely.
- The same entities are replaced with the respective characters by
  clean_html, resulting in an invalid JSON.

At the reviewer's suggestion, replaced _html_search_regex with
_search_json to resolve both issues.

Signed-off-by: Alexey Neyman <stilor@att.net>