Update aenetworks.py
When using yt-dlp on a series page it was giving 

ValueError: too many values to unpack (expected 2)

Once I fixed that, then was getting 400 on the graphql call. So switched to json.dumps to fix it.